/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import BaseDatos.BaseDatos;
import ModeloAlbum.Albums;
import ModelosPersona.Metodos;
import ModelosPersona.Personas;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia Díaz Rendón
 */
public class Login extends javax.swing.JFrame {
    private static BaseDatos database = new BaseDatos();
    public ArrayList<Personas> lista_personas = Metodos.obtenerTodos();
    public static Usuario usuario = new Usuario();
    private int aprobado=0;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jTextCorreo = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jButtonEntrar = new javax.swing.JButton();

        jLabel1.setText("FOTO");

        jLabelCorreo.setText("Correo");

        jLabelPassword.setText("Password");

        jPassword.setText("jPasswordField1");

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCorreo)
                            .addComponent(jTextCorreo)
                            .addComponent(jLabelPassword)
                            .addComponent(jPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jButtonEntrar)))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jLabelCorreo)
                .addGap(18, 18, 18)
                .addComponent(jTextCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword)
                .addGap(18, 18, 18)
                .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEntrar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
       if(jTextCorreo.getText().isEmpty()||jPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Le faltan Campos vacios por llenar", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            switch(evt.getActionCommand())
            { 
                
                case "Entrar":
                    validarUsuario();
                    if(aprobado>0){
                        JFZonaUsuario obj = new JFZonaUsuario();
                        obj.setVisible(true);
                    
                    }else{
                         JOptionPane.showMessageDialog(this, "Error en sus datos", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                 break;
                
            }
            
           // this.refreshTableModel();
           //this.resetForm();
            
        }
    }//GEN-LAST:event_jButtonEntrarActionPerformed
    private void validarUsuario(){
       for(Personas p : lista_personas){
         
          if((p.getEmail().equals(jTextCorreo.getText())) && (p.getPassword().equals(jPassword.getText()))){
              usuario = new Usuario(p.getDocumento(), p.getNombre(), p.getApellido(), p.getPassword(), p.getTelefono(), p.getEmail(),p.getFoto());
              aprobado++;
          }
        }
    }
    
    
    /**
     * Convierte el formulario a blanco
     */
    private void resetForm() {
        jTextCorreo.setText("");
        jPassword.setText("");
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextCorreo;
    // End of variables declaration//GEN-END:variables
}
