/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModeloCompra;

/**
 *
 * @author Familia Díaz Rendón
 */
public class Comprar extends javax.swing.JPanel {

    /**
     * Creates new form Comprar
     */
    public Comprar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBusAlbum = new javax.swing.JButton();
        jButtonBusArtista = new javax.swing.JButton();
        jButtonBusCanciones = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButtonBusAlbum.setText("Buscar Album");
        jButtonBusAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusAlbumActionPerformed(evt);
            }
        });

        jButtonBusArtista.setText("Buscar Artista");
        jButtonBusArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusArtistaActionPerformed(evt);
            }
        });

        jButtonBusCanciones.setText("Buscar Canciones");
        jButtonBusCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBusCancionesActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("COMPRAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButtonBusAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonBusArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButtonBusCanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBusArtista)
                    .addComponent(jButtonBusAlbum)
                    .addComponent(jButtonBusCanciones))
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBusAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBusAlbumActionPerformed

    private void jButtonBusArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBusArtistaActionPerformed

    private void jButtonBusCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBusCancionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBusCancionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBusAlbum;
    private javax.swing.JButton jButtonBusArtista;
    private javax.swing.JButton jButtonBusCanciones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
