package ModelosPersona;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;



/**
 *
 * @author Jona
 */
public class JPanelRegistro extends javax.swing.JPanel {
    
    private String foto="";
    private Personas persona;
    
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes: PNG, JPG", "png", "jpg");
    private  JFileChooser jfcImagen = new JFileChooser();
    /**
     * Creates new form Panel
     */
    
    public JPanelRegistro() {
        initComponents();
        jfcImagen.setFileFilter(filtro);
        jfcImagen.setDialogTitle("Seleccione una imagen");
        jfcImagen.setAcceptAllFileFilterUsed(false);
        jlImagen.setBackground(Color.white);
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        label_documento = new javax.swing.JLabel();
        text_documento = new javax.swing.JTextField();
        jlabel_nombre = new javax.swing.JLabel();
        text_nombre = new javax.swing.JTextField();
        label_telefono = new javax.swing.JLabel();
        text_telefono = new javax.swing.JTextField();
        label_email = new javax.swing.JLabel();
        text_email = new javax.swing.JTextField();
        button_guardar = new javax.swing.JButton();
        button_cancelar = new javax.swing.JButton();
        jLabelApellido = new javax.swing.JLabel();
        jTextApellido = new javax.swing.JTextField();
        Titulo = new javax.swing.JLabel();
        jLabelpassword = new javax.swing.JLabel();
        jButtonImagen = new javax.swing.JButton();
        jlImagen = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();

        label_documento.setText("Documento");

        text_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_documentoActionPerformed(evt);
            }
        });

        jlabel_nombre.setText("Nombre");

        label_telefono.setText("Teléfono");

        text_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_telefonoActionPerformed(evt);
            }
        });

        label_email.setText("Email");

        button_guardar.setText("Guardar");
        button_guardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        button_guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_guardarActionPerformed(evt);
            }
        });

        button_cancelar.setText("Cancelar");
        button_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelarActionPerformed(evt);
            }
        });

        jLabelApellido.setText("Apellido");

        jTextApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApellidoActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 14)); // NOI18N
        Titulo.setText("REGISTRO USUARIOS");

        jLabelpassword.setText("Password");

        jButtonImagen.setText("SeleccionarImagen");
        jButtonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagenActionPerformed(evt);
            }
        });

        jPassword.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(jlImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_documento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label_telefono)
                        .addGap(178, 178, 178)
                        .addComponent(label_email))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_guardar)
                            .addComponent(text_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button_cancelar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(text_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(jlabel_nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_documento, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelApellido)
                            .addComponent(jTextApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jLabelpassword)
                            .addComponent(jPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Titulo)
                        .addGap(223, 223, 223)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(64, Short.MAX_VALUE)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel_nombre)
                            .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_documento)
                            .addComponent(jLabelpassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_telefono)
                            .addComponent(label_email))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jlImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonImagen)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_guardar)
                    .addComponent(button_cancelar))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void text_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_documentoActionPerformed

    private void text_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_telefonoActionPerformed

    private void button_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_guardarActionPerformed
       
        if( text_documento.getText().isEmpty() ||
            text_nombre.getText().isEmpty() ||
            text_telefono.getText().isEmpty() || 
            text_email.getText().isEmpty()||
            jPassword.getText().isEmpty() || jTextApellido.getText().isEmpty()
        ){
            JOptionPane.showMessageDialog(this, "Por favor diligencie todo el formulario", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            switch(evt.getActionCommand())
            { 
                
                case "Guardar":
                    
                    persona = Personas.crear(Integer.valueOf(text_documento.getText()), text_nombre.getText(),jTextApellido.getText(),jPassword.getText(), Integer.valueOf(text_telefono.getText()), text_email.getText(),foto);
                    Metodos.crear(persona);
                    JOptionPane.showMessageDialog(this, "Su usuario ha sido creado", "Genial", JOptionPane.INFORMATION_MESSAGE);
                break;
                
            }
            
           // this.refreshTableModel();
            this.resetForm();
            this.resetPersona();
        }
    }//GEN-LAST:event_button_guardarActionPerformed

    private void button_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelarActionPerformed
        resetForm();
    }//GEN-LAST:event_button_cancelarActionPerformed

    private void jTextApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApellidoActionPerformed
       
    }//GEN-LAST:event_jTextApellidoActionPerformed
    
    private void jButtonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagenActionPerformed
       int valor = jfcImagen.showOpenDialog(null);
            
            if(valor == JFileChooser.APPROVE_OPTION){
                File archivo = jfcImagen.getSelectedFile();
                
                Image img = obtenerImagen(archivo.getPath());
                img = redimencionarImagen(img, jlImagen.getWidth(), jlImagen.getHeight());
                mostrarImagen(img);
                
            }
    }//GEN-LAST:event_jButtonImagenActionPerformed
    /**
     * Convierte el formulario a blanco
     */
    private void resetForm() {
        text_documento.setText("");
        text_nombre.setText("");
        jTextApellido.setText("");
        jPassword.setText("");
        text_telefono.setText("");
        text_email.setText("");
        jlImagen.setText("");
    }
    /**
     * Limpia el objeto Persona
     */
    private void resetPersona() {

        persona.setDocumento(0);
        persona.setEmail("");
        persona.setNombre("");
        persona.setApellido("");
        persona.setPassword("");
        persona.setTelefono(0);
        persona.setFoto("");
        
    }
    /**
     * Obtiene la Imagen 
     * @param url
     * @return 
     */
    public Image obtenerImagen(String url){
        
        Image img = Toolkit.getDefaultToolkit().getImage(url);
        foto=url;
        System.out.println(foto);
        return img;
    }
    /**
     * Permite organizar la imagen al tamaño del Jlabel
     * @param img
     * @param ancho
     * @param alto
     * @return 
     */
    public Image redimencionarImagen(Image img, int ancho, int alto){
        return img.getScaledInstance(ancho, alto, Image.SCALE_AREA_AVERAGING);
    }
    /**
     * Muestra la imagen seleccionada
     * @param img 
     */
    public void mostrarImagen(Image img){
        ImageIcon icono = new ImageIcon(img);
        jlImagen.setIcon(icono);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton button_cancelar;
    private javax.swing.JButton button_guardar;
    private javax.swing.JButton jButtonImagen;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelpassword;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JLabel jlImagen;
    private javax.swing.JLabel jlabel_nombre;
    private javax.swing.JLabel label_documento;
    private javax.swing.JLabel label_email;
    private javax.swing.JLabel label_telefono;
    private javax.swing.JTextField text_documento;
    private javax.swing.JTextField text_email;
    private javax.swing.JTextField text_nombre;
    private javax.swing.JTextField text_telefono;
    // End of variables declaration//GEN-END:variables
}
