/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModelosPersona;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia Díaz Rendón
 */
public class Usuarios extends javax.swing.JPanel {
    private DefaultTableModel table_model_personas;
    public ArrayList<Personas> lista_personas = Metodos.obtenerTodos();
   
    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
        configComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_personas = new javax.swing.JTable();

        tabla_personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_personas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void configComponents() {
        
        
        DefaultTableModel table_model_personas = new DefaultTableModel();
        
        table_model_personas.addColumn("Documento");
        table_model_personas.addColumn("Nombre");
        table_model_personas.addColumn("Apellido");
        table_model_personas.addColumn("Email");
        table_model_personas.addColumn("foto");
        tabla_personas.setModel(table_model_personas);
        this.setTableModel(table_model_personas);
        this.refreshTableModel();
    }
    public void setTableModel(DefaultTableModel table_model_personas){
        this.table_model_personas = table_model_personas;
    }
    
    
    
    public void refreshTableModel()
    {
        
       while (table_model_personas.getRowCount() > 0) {
            table_model_personas.removeRow(0);
        }
       
         for(Personas p : lista_personas){
            Image img = Toolkit.getDefaultToolkit().getImage(p.getFoto()); 
            ImageIcon icono = new ImageIcon(img);
            Object[] data = {Integer.toString(p.getDocumento()), p.getNombre(), p.getApellido(),  p.getEmail(), new JLabel(icono)};
            table_model_personas.addRow(data);
         }
    }
  
    
  
  
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_personas;
    // End of variables declaration//GEN-END:variables
}
