/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModeloAlbum;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Familia Díaz Rendón
 */
public class RegistroDisco extends javax.swing.JPanel {
    
    private Albums albun;
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes: PNG, JPG", "png", "jpg");
    private JFileChooser jfcImagen = new JFileChooser();
    private String foto="";
    /**
     * Creates new form RegistroCancion
     */
    public RegistroDisco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomAlb = new javax.swing.JLabel();
        jTextNomAlb = new javax.swing.JTextField();
        jLabelArtista = new javax.swing.JLabel();
        jTextArtista = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextGenero = new javax.swing.JTextField();
        jLabelImagenCara = new javax.swing.JLabel();
        ImagenTotal = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        SleccionImagen = new javax.swing.JButton();

        jLabelNomAlb.setText("Nombre Album:");

        jLabelArtista.setText("Artista:");

        jLabelGenero.setText("Genero:");

        jTextGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGeneroActionPerformed(evt);
            }
        });

        jLabelImagenCara.setText("Imagen de la Caratula");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        SleccionImagen.setText("Seleccionar Imagen");
        SleccionImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SleccionImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(291, 291, 291)
                            .addComponent(jLabelImagenCara))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextNomAlb, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(SleccionImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelNomAlb)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ImagenTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelArtista)
                                .addComponent(jTextArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelImagenCara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ImagenTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNomAlb)
                    .addComponent(jLabelArtista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextNomAlb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SleccionImagen))
                .addGap(18, 18, 18)
                .addComponent(jLabelGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGeneroActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
          if( jTextNomAlb.getText().isEmpty() || jTextArtista.getText().isEmpty()||jTextGenero.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor diligencie todo el formulario", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            switch(evt.getActionCommand())
            { 
                
                case "Guardar":
                    albun = Albums.crear(jTextNomAlb.getText(),jTextArtista.getText(),jTextGenero.getText(),foto);
                    MetodosAlbum.crear(albun);
                    JOptionPane.showMessageDialog(this, "Su Album o Disco ha sido creado", "Genial", JOptionPane.INFORMATION_MESSAGE);
                break;
                
            }
            resetForm();
          
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed
      /**
     * Convierte el formulario a blanco
     */
    private void resetForm() {
        jTextNomAlb.setText("");
        jTextArtista.setText("");
        jTextGenero.setText("");
        
    }
    
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        resetForm();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void SleccionImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SleccionImagenActionPerformed
        int valor = jfcImagen.showOpenDialog(null);
            
            if(valor == JFileChooser.APPROVE_OPTION){
                File archivo = jfcImagen.getSelectedFile();
                
                Image img = obtenerImagen(archivo.getPath());
                img = redimencionarImagen(img, ImagenTotal.getWidth(), ImagenTotal.getHeight());
                mostrarImagen(img);
                
            }
    }//GEN-LAST:event_SleccionImagenActionPerformed
     /**
     * Obtiene la Imagen 
     * @param url
     * @return 
     */
    public Image obtenerImagen(String url){
        
        Image img = Toolkit.getDefaultToolkit().getImage(url);
        foto=url;
        return img;
    }
    /**
     * Permite organizar la imagen al tamaño del Jlabel
     * @param img
     * @param ancho
     * @param alto
     * @return 
     */
    public Image redimencionarImagen(Image img, int ancho, int alto){
        return img.getScaledInstance(ancho, alto, Image.SCALE_AREA_AVERAGING);
    }
    /**
     * Muestra la imagen seleccionada
     * @param img 
     */
    public void mostrarImagen(Image img){
        ImageIcon icono = new ImageIcon(img);
       ImagenTotal.setIcon(icono);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenTotal;
    private javax.swing.JButton SleccionImagen;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabelArtista;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelImagenCara;
    private javax.swing.JLabel jLabelNomAlb;
    private javax.swing.JTextField jTextArtista;
    private javax.swing.JTextField jTextGenero;
    private javax.swing.JTextField jTextNomAlb;
    // End of variables declaration//GEN-END:variables
}
